name: inspecao_seguranca
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.3.0+12

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  get_it: ^7.6.0
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  cloud_firestore: ^4.14.0
  pdf: ^3.10.7
  syncfusion_flutter_pdfviewer: ^24.1.45
  bloc: ^8.1.2
  equatable: ^2.0.5
  injectable: ^2.2.0
  json_annotation: ^4.8.1
  logging: ^1.2.0
  getwidget: ^4.0.0
  uuid: ^4.0.0
  external_path: ^1.0.3
  flutter_typeahead: ^5.0.2
  syncfusion_flutter_xlsio: ^24.1.45
  open_file: ^3.2.1
  font_awesome_flutter: ^10.6.0
  shared_preferences: ^2.2.2
  firebase_app_check: ^0.2.1+8
  mask_text_input_formatter: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mobx_codegen: ^2.3.0
  build_runner: ^2.4.6
  injectable_generator: ^2.3.0
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1
flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
